### ISSUE TITLE
Disable other players added to region to use /ps allow

### ISSUE THREAD

**Issue by arturek1666** [marcelo-mason/PreciousStones#1037]
Please add the feature so only owner of block can add players to region.

**Comment by marcelo-mason** [comment]
Didn't have time to test the feature.  Let me know if its working.  You should be able to use /ps allow -g someplayer to make him a guest and he should get an error message if he tries to allow someone into the field.

**Comment by dwa1275** [comment]
so /ps allow -g (name) is the command?

**Comment by dwa1275** [comment]
command works, is there a way to add this as a flag so that all members added threw /ps allow (name) will always be added as a guest? this would be so much more helpful as I have a war on my server and players that are spies are allowing other clan member to a ps field that they should not be able to
