### ISSUE TITLE
Newest server version is on its way

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#1067]
Hi,

As the title says, i've been trying out my server with latest spigot 1.12 software (test test test ofcourse) and wanted to tell you, because your plugin is important to a lot of people, the last version you made is not compatible with newest version of Spigot.

**Comment by marcelo-mason** [comment]
Will check on this

On May 15, 2017 2:58 PM, "MrKiller01" <notifications@github.com> wrote:

Hi,

As the title says, i've been trying out my server with latest spigot 1.12
software (test test test ofcourse) and wanted to tell you, because your
plugin is important to a lot of people, the last version you made is not
compatible with newest version of Spigot.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/marcelo-mason/PreciousStones/issues/1067>, or mute the
thread

**Comment by MrKiller01** [comment]
Thanks, out of a few devs i told about their plugins, you were the only one giving response....
Hope  that everything goes according to plan....
oh, and thanks again in advance...

**Comment by marcelo-mason** [comment]
It up
