### ISSUE TITLE
TreeFeller and preciosstones issue 

### ISSUE THREAD

**Issue by arturek1666** [marcelo-mason/PreciousStones#1098]
Hi, i had notice that precios stones don't protect when one plugin is installed with is treefeller, What i mean is that people can broke wood from protected region. I am not sure if i have to report to the treefeller author or preciosstones and that's why I first informed here.

I am using newest version of paperspigot and newest preciosstones for 1.12

**Comment by marcelo-mason** [comment]
Ideally, the priority to their BlockBreakEvent should be set to `EventPriority.HIGH` one below what protection plugins use  `EventPriority.HIGHEST` , to allow them to cancel the event.   Otherwise, they would have to hook into [PS Api](https://github.com/marcelo-mason/PreciousStones/wiki/Developers-API) to see if the area is protected before allowing block-break.
