### ISSUE TITLE
/setblock to place fields?

### ISSUE THREAD

**Issue by Tygah** [marcelo-mason/PreciousStones#956]
Hey there, I'm trying to find a way for the console to automatically place fields, namely the Forester fields. However, when the /setblock command is used it places the block, but it doesn't activate the field. Is there a way to make it so that I can place the block and the field simultaneously with a command, rather than having to have a player do it?

If not, is there a way to make this a feature? Thanks a bunch!

**Comment by spetznack** [comment]
This would save a ton of work and be very useful for my temporary maps! Hmm.. But how would this be done.. We don't want /setblock to automatically create a field because that has potential to unintentionally create fields. I'm thinking something like this: /ps placefield [x] [y] [z] <owner> <world>

If a player with permission use this command, a field will be placed in the given coordinates in the world the player is in - unless a world is specified. If the command is executed through a command block or console, then I think the <world> parameter has to be required for it to work. 

I'm not sure if preciousstones will need the UUID or if it can somehow just take the playername for the <owner> parameter, but obviously this should be a requirement as well if executed through command block or console. What would happen if a field doesn't have a owner anyway? :P
